export const myMsg = {
  userNA: "User Not Found!",
  multipleUser: "User Exists. Cannot add multiple",
  userCreated: "User created Successfully!",
  passwordNoMatch: "Password do not match!",
  signinSuccess: "Logged In successsfully!",
  tokenExpired: "Token Expired. Pls login again",
  GETvehicleSuccess: "Fetched Vehicles Successfully!",
  GETsuccess: "Fetched Data Successfully!",
  POSTsuccess: "Data Added Successfully!",
  DELsuccess: "Deleted Successfully!",
  PUTsuccess: "Edited Successfully!",
  PATCHsuccess: "Published Successfully!",
  tokenNA: "No Token Provided!",
  duplicateUsername: "Duplicate Username",
  failedSaving: "Failed while saving",
  searchSuccess: "Searched Successfully!",
  profileNA: "User Profile Not Found! Signup with new account!",
  serverErrorPOST: "Server Error: while posting data",
  serverError: "Server Error:",
  notSuperAdmin: "User isn't Super Admin",
  notAdmin: "User isn't Admin",
  docExists: "Duplicate Document found in database.",
  alreadyPublished: "Document is already published.",
  googleSignErr: "Google Signin Error.",
  invalidBody: "Invalid Body!",
  idlength: "Id length too high!",
};
