import React from "react";

const ShareTable = () => {
  return (
    <div>
      <table className="">
        <thead>
          <tr>
            <th>Symbol</th>
            <th>LTP</th>
            <th>Chg</th>
            <th>% Chg</th>
            <th>Max Price</th>
            <th>Min Price</th>
            <th>Open</th>
            <th>Qty</th>
            <th>Txn</th>
          </tr>
        </thead>
        <tbody>
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-red-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-red-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>{" "}
          <tr className="bg-green-500">
            <td className="">ALICL</td>
            <td className="">846.35</td>
            <td className="">122</td>
            <td className="">1.33</td>
            <td className="">849.00</td>
            <td className="">844.00</td>
            <td className="">846.00</td>
            <td className="">1,00,000</td>
            <td className="">1,00,000</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};

export default ShareTable;
