// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/investment"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/portfolio"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/predicate"
)

// InvestmentQuery is the builder for querying Investment entities.
type InvestmentQuery struct {
	config
	limit            *int
	offset           *int
	unique           *bool
	order            []OrderFunc
	fields           []string
	predicates       []predicate.Investment
	withInvestmentID *PortfolioQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InvestmentQuery builder.
func (iq *InvestmentQuery) Where(ps ...predicate.Investment) *InvestmentQuery {
	iq.predicates = append(iq.predicates, ps...)
	return iq
}

// Limit adds a limit step to the query.
func (iq *InvestmentQuery) Limit(limit int) *InvestmentQuery {
	iq.limit = &limit
	return iq
}

// Offset adds an offset step to the query.
func (iq *InvestmentQuery) Offset(offset int) *InvestmentQuery {
	iq.offset = &offset
	return iq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iq *InvestmentQuery) Unique(unique bool) *InvestmentQuery {
	iq.unique = &unique
	return iq
}

// Order adds an order step to the query.
func (iq *InvestmentQuery) Order(o ...OrderFunc) *InvestmentQuery {
	iq.order = append(iq.order, o...)
	return iq
}

// QueryInvestmentID chains the current query on the "investment_id" edge.
func (iq *InvestmentQuery) QueryInvestmentID() *PortfolioQuery {
	query := &PortfolioQuery{config: iq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(investment.Table, investment.FieldID, selector),
			sqlgraph.To(portfolio.Table, portfolio.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, investment.InvestmentIDTable, investment.InvestmentIDColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Investment entity from the query.
// Returns a *NotFoundError when no Investment was found.
func (iq *InvestmentQuery) First(ctx context.Context) (*Investment, error) {
	nodes, err := iq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{investment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iq *InvestmentQuery) FirstX(ctx context.Context) *Investment {
	node, err := iq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Investment ID from the query.
// Returns a *NotFoundError when no Investment ID was found.
func (iq *InvestmentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = iq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{investment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iq *InvestmentQuery) FirstIDX(ctx context.Context) int {
	id, err := iq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Investment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Investment entity is found.
// Returns a *NotFoundError when no Investment entities are found.
func (iq *InvestmentQuery) Only(ctx context.Context) (*Investment, error) {
	nodes, err := iq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{investment.Label}
	default:
		return nil, &NotSingularError{investment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iq *InvestmentQuery) OnlyX(ctx context.Context) *Investment {
	node, err := iq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Investment ID in the query.
// Returns a *NotSingularError when more than one Investment ID is found.
// Returns a *NotFoundError when no entities are found.
func (iq *InvestmentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = iq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{investment.Label}
	default:
		err = &NotSingularError{investment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iq *InvestmentQuery) OnlyIDX(ctx context.Context) int {
	id, err := iq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Investments.
func (iq *InvestmentQuery) All(ctx context.Context) ([]*Investment, error) {
	if err := iq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return iq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (iq *InvestmentQuery) AllX(ctx context.Context) []*Investment {
	nodes, err := iq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Investment IDs.
func (iq *InvestmentQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := iq.Select(investment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iq *InvestmentQuery) IDsX(ctx context.Context) []int {
	ids, err := iq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iq *InvestmentQuery) Count(ctx context.Context) (int, error) {
	if err := iq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return iq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (iq *InvestmentQuery) CountX(ctx context.Context) int {
	count, err := iq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iq *InvestmentQuery) Exist(ctx context.Context) (bool, error) {
	if err := iq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return iq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (iq *InvestmentQuery) ExistX(ctx context.Context) bool {
	exist, err := iq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InvestmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iq *InvestmentQuery) Clone() *InvestmentQuery {
	if iq == nil {
		return nil
	}
	return &InvestmentQuery{
		config:           iq.config,
		limit:            iq.limit,
		offset:           iq.offset,
		order:            append([]OrderFunc{}, iq.order...),
		predicates:       append([]predicate.Investment{}, iq.predicates...),
		withInvestmentID: iq.withInvestmentID.Clone(),
		// clone intermediate query.
		sql:    iq.sql.Clone(),
		path:   iq.path,
		unique: iq.unique,
	}
}

// WithInvestmentID tells the query-builder to eager-load the nodes that are connected to
// the "investment_id" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *InvestmentQuery) WithInvestmentID(opts ...func(*PortfolioQuery)) *InvestmentQuery {
	query := &PortfolioQuery{config: iq.config}
	for _, opt := range opts {
		opt(query)
	}
	iq.withInvestmentID = query
	return iq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Investment.Query().
//		GroupBy(investment.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (iq *InvestmentQuery) GroupBy(field string, fields ...string) *InvestmentGroupBy {
	grbuild := &InvestmentGroupBy{config: iq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return iq.sqlQuery(ctx), nil
	}
	grbuild.label = investment.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//	}
//
//	client.Investment.Query().
//		Select(investment.FieldUserID).
//		Scan(ctx, &v)
func (iq *InvestmentQuery) Select(fields ...string) *InvestmentSelect {
	iq.fields = append(iq.fields, fields...)
	selbuild := &InvestmentSelect{InvestmentQuery: iq}
	selbuild.label = investment.Label
	selbuild.flds, selbuild.scan = &iq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a InvestmentSelect configured with the given aggregations.
func (iq *InvestmentQuery) Aggregate(fns ...AggregateFunc) *InvestmentSelect {
	return iq.Select().Aggregate(fns...)
}

func (iq *InvestmentQuery) prepareQuery(ctx context.Context) error {
	for _, f := range iq.fields {
		if !investment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iq.path != nil {
		prev, err := iq.path(ctx)
		if err != nil {
			return err
		}
		iq.sql = prev
	}
	return nil
}

func (iq *InvestmentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Investment, error) {
	var (
		nodes       = []*Investment{}
		withFKs     = iq.withFKs
		_spec       = iq.querySpec()
		loadedTypes = [1]bool{
			iq.withInvestmentID != nil,
		}
	)
	if iq.withInvestmentID != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, investment.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Investment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Investment{config: iq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, iq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := iq.withInvestmentID; query != nil {
		if err := iq.loadInvestmentID(ctx, query, nodes, nil,
			func(n *Investment, e *Portfolio) { n.Edges.InvestmentID = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (iq *InvestmentQuery) loadInvestmentID(ctx context.Context, query *PortfolioQuery, nodes []*Investment, init func(*Investment), assign func(*Investment, *Portfolio)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Investment)
	for i := range nodes {
		if nodes[i].portfolio_investments == nil {
			continue
		}
		fk := *nodes[i].portfolio_investments
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(portfolio.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "portfolio_investments" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (iq *InvestmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iq.querySpec()
	_spec.Node.Columns = iq.fields
	if len(iq.fields) > 0 {
		_spec.Unique = iq.unique != nil && *iq.unique
	}
	return sqlgraph.CountNodes(ctx, iq.driver, _spec)
}

func (iq *InvestmentQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := iq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (iq *InvestmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   investment.Table,
			Columns: investment.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: investment.FieldID,
			},
		},
		From:   iq.sql,
		Unique: true,
	}
	if unique := iq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := iq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, investment.FieldID)
		for i := range fields {
			if fields[i] != investment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iq *InvestmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iq.driver.Dialect())
	t1 := builder.Table(investment.Table)
	columns := iq.fields
	if len(columns) == 0 {
		columns = investment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iq.sql != nil {
		selector = iq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iq.unique != nil && *iq.unique {
		selector.Distinct()
	}
	for _, p := range iq.predicates {
		p(selector)
	}
	for _, p := range iq.order {
		p(selector)
	}
	if offset := iq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// InvestmentGroupBy is the group-by builder for Investment entities.
type InvestmentGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (igb *InvestmentGroupBy) Aggregate(fns ...AggregateFunc) *InvestmentGroupBy {
	igb.fns = append(igb.fns, fns...)
	return igb
}

// Scan applies the group-by query and scans the result into the given value.
func (igb *InvestmentGroupBy) Scan(ctx context.Context, v any) error {
	query, err := igb.path(ctx)
	if err != nil {
		return err
	}
	igb.sql = query
	return igb.sqlScan(ctx, v)
}

func (igb *InvestmentGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range igb.fields {
		if !investment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := igb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := igb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (igb *InvestmentGroupBy) sqlQuery() *sql.Selector {
	selector := igb.sql.Select()
	aggregation := make([]string, 0, len(igb.fns))
	for _, fn := range igb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(igb.fields)+len(igb.fns))
		for _, f := range igb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(igb.fields...)...)
}

// InvestmentSelect is the builder for selecting fields of Investment entities.
type InvestmentSelect struct {
	*InvestmentQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (is *InvestmentSelect) Aggregate(fns ...AggregateFunc) *InvestmentSelect {
	is.fns = append(is.fns, fns...)
	return is
}

// Scan applies the selector query and scans the result into the given value.
func (is *InvestmentSelect) Scan(ctx context.Context, v any) error {
	if err := is.prepareQuery(ctx); err != nil {
		return err
	}
	is.sql = is.InvestmentQuery.sqlQuery(ctx)
	return is.sqlScan(ctx, v)
}

func (is *InvestmentSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(is.fns))
	for _, fn := range is.fns {
		aggregation = append(aggregation, fn(is.sql))
	}
	switch n := len(*is.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		is.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		is.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := is.sql.Query()
	if err := is.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
