// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/investment"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/portfolio"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/transaction"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/user"
)

// PortfolioCreate is the builder for creating a Portfolio entity.
type PortfolioCreate struct {
	config
	mutation *PortfolioMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pc *PortfolioCreate) SetName(s string) *PortfolioCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetAdminName sets the "admin_name" field.
func (pc *PortfolioCreate) SetAdminName(s string) *PortfolioCreate {
	pc.mutation.SetAdminName(s)
	return pc
}

// SetDate sets the "date" field.
func (pc *PortfolioCreate) SetDate(s string) *PortfolioCreate {
	pc.mutation.SetDate(s)
	return pc
}

// SetCreatedAt sets the "created_at" field.
func (pc *PortfolioCreate) SetCreatedAt(t time.Time) *PortfolioCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableCreatedAt(t *time.Time) *PortfolioCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetUpdatedAt sets the "updated_at" field.
func (pc *PortfolioCreate) SetUpdatedAt(t time.Time) *PortfolioCreate {
	pc.mutation.SetUpdatedAt(t)
	return pc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableUpdatedAt(t *time.Time) *PortfolioCreate {
	if t != nil {
		pc.SetUpdatedAt(*t)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *PortfolioCreate) SetID(i int) *PortfolioCreate {
	pc.mutation.SetID(i)
	return pc
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (pc *PortfolioCreate) AddTransactionIDs(ids ...int) *PortfolioCreate {
	pc.mutation.AddTransactionIDs(ids...)
	return pc
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (pc *PortfolioCreate) AddTransactions(t ...*Transaction) *PortfolioCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return pc.AddTransactionIDs(ids...)
}

// AddInvestmentIDs adds the "investments" edge to the Investment entity by IDs.
func (pc *PortfolioCreate) AddInvestmentIDs(ids ...int) *PortfolioCreate {
	pc.mutation.AddInvestmentIDs(ids...)
	return pc
}

// AddInvestments adds the "investments" edges to the Investment entity.
func (pc *PortfolioCreate) AddInvestments(i ...*Investment) *PortfolioCreate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return pc.AddInvestmentIDs(ids...)
}

// SetUserIDID sets the "user_id" edge to the User entity by ID.
func (pc *PortfolioCreate) SetUserIDID(id int) *PortfolioCreate {
	pc.mutation.SetUserIDID(id)
	return pc
}

// SetNillableUserIDID sets the "user_id" edge to the User entity by ID if the given value is not nil.
func (pc *PortfolioCreate) SetNillableUserIDID(id *int) *PortfolioCreate {
	if id != nil {
		pc = pc.SetUserIDID(*id)
	}
	return pc
}

// SetUserID sets the "user_id" edge to the User entity.
func (pc *PortfolioCreate) SetUserID(u *User) *PortfolioCreate {
	return pc.SetUserIDID(u.ID)
}

// Mutation returns the PortfolioMutation object of the builder.
func (pc *PortfolioCreate) Mutation() *PortfolioMutation {
	return pc.mutation
}

// Save creates the Portfolio in the database.
func (pc *PortfolioCreate) Save(ctx context.Context) (*Portfolio, error) {
	var (
		err  error
		node *Portfolio
	)
	pc.defaults()
	if len(pc.hooks) == 0 {
		if err = pc.check(); err != nil {
			return nil, err
		}
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PortfolioMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pc.check(); err != nil {
				return nil, err
			}
			pc.mutation = mutation
			if node, err = pc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			if pc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, pc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Portfolio)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PortfolioMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PortfolioCreate) SaveX(ctx context.Context) *Portfolio {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PortfolioCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PortfolioCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PortfolioCreate) defaults() {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		v := portfolio.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		v := portfolio.DefaultUpdatedAt()
		pc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PortfolioCreate) check() error {
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Portfolio.name"`)}
	}
	if _, ok := pc.mutation.AdminName(); !ok {
		return &ValidationError{Name: "admin_name", err: errors.New(`ent: missing required field "Portfolio.admin_name"`)}
	}
	if _, ok := pc.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "Portfolio.date"`)}
	}
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Portfolio.created_at"`)}
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Portfolio.updated_at"`)}
	}
	return nil
}

func (pc *PortfolioCreate) sqlSave(ctx context.Context) (*Portfolio, error) {
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (pc *PortfolioCreate) createSpec() (*Portfolio, *sqlgraph.CreateSpec) {
	var (
		_node = &Portfolio{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: portfolio.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: portfolio.FieldID,
			},
		}
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(portfolio.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.AdminName(); ok {
		_spec.SetField(portfolio.FieldAdminName, field.TypeString, value)
		_node.AdminName = &value
	}
	if value, ok := pc.mutation.Date(); ok {
		_spec.SetField(portfolio.FieldDate, field.TypeString, value)
		_node.Date = value
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.SetField(portfolio.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.SetField(portfolio.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := pc.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   portfolio.TransactionsTable,
			Columns: []string{portfolio.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: transaction.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.InvestmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   portfolio.InvestmentsTable,
			Columns: []string{portfolio.InvestmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: investment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.UserIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   portfolio.UserIDTable,
			Columns: []string{portfolio.UserIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_portfolios = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PortfolioCreateBulk is the builder for creating many Portfolio entities in bulk.
type PortfolioCreateBulk struct {
	config
	builders []*PortfolioCreate
}

// Save creates the Portfolio entities in the database.
func (pcb *PortfolioCreateBulk) Save(ctx context.Context) ([]*Portfolio, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Portfolio, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PortfolioMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PortfolioCreateBulk) SaveX(ctx context.Context) []*Portfolio {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PortfolioCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PortfolioCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
