// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/investment"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/portfolio"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/predicate"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/transaction"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/user"
)

// PortfolioQuery is the builder for querying Portfolio entities.
type PortfolioQuery struct {
	config
	limit            *int
	offset           *int
	unique           *bool
	order            []OrderFunc
	fields           []string
	predicates       []predicate.Portfolio
	withTransactions *TransactionQuery
	withInvestments  *InvestmentQuery
	withUserID       *UserQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PortfolioQuery builder.
func (pq *PortfolioQuery) Where(ps ...predicate.Portfolio) *PortfolioQuery {
	pq.predicates = append(pq.predicates, ps...)
	return pq
}

// Limit adds a limit step to the query.
func (pq *PortfolioQuery) Limit(limit int) *PortfolioQuery {
	pq.limit = &limit
	return pq
}

// Offset adds an offset step to the query.
func (pq *PortfolioQuery) Offset(offset int) *PortfolioQuery {
	pq.offset = &offset
	return pq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pq *PortfolioQuery) Unique(unique bool) *PortfolioQuery {
	pq.unique = &unique
	return pq
}

// Order adds an order step to the query.
func (pq *PortfolioQuery) Order(o ...OrderFunc) *PortfolioQuery {
	pq.order = append(pq.order, o...)
	return pq
}

// QueryTransactions chains the current query on the "transactions" edge.
func (pq *PortfolioQuery) QueryTransactions() *TransactionQuery {
	query := &TransactionQuery{config: pq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(portfolio.Table, portfolio.FieldID, selector),
			sqlgraph.To(transaction.Table, transaction.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, portfolio.TransactionsTable, portfolio.TransactionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryInvestments chains the current query on the "investments" edge.
func (pq *PortfolioQuery) QueryInvestments() *InvestmentQuery {
	query := &InvestmentQuery{config: pq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(portfolio.Table, portfolio.FieldID, selector),
			sqlgraph.To(investment.Table, investment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, portfolio.InvestmentsTable, portfolio.InvestmentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUserID chains the current query on the "user_id" edge.
func (pq *PortfolioQuery) QueryUserID() *UserQuery {
	query := &UserQuery{config: pq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(portfolio.Table, portfolio.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, portfolio.UserIDTable, portfolio.UserIDColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Portfolio entity from the query.
// Returns a *NotFoundError when no Portfolio was found.
func (pq *PortfolioQuery) First(ctx context.Context) (*Portfolio, error) {
	nodes, err := pq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{portfolio.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pq *PortfolioQuery) FirstX(ctx context.Context) *Portfolio {
	node, err := pq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Portfolio ID from the query.
// Returns a *NotFoundError when no Portfolio ID was found.
func (pq *PortfolioQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{portfolio.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pq *PortfolioQuery) FirstIDX(ctx context.Context) int {
	id, err := pq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Portfolio entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Portfolio entity is found.
// Returns a *NotFoundError when no Portfolio entities are found.
func (pq *PortfolioQuery) Only(ctx context.Context) (*Portfolio, error) {
	nodes, err := pq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{portfolio.Label}
	default:
		return nil, &NotSingularError{portfolio.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pq *PortfolioQuery) OnlyX(ctx context.Context) *Portfolio {
	node, err := pq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Portfolio ID in the query.
// Returns a *NotSingularError when more than one Portfolio ID is found.
// Returns a *NotFoundError when no entities are found.
func (pq *PortfolioQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{portfolio.Label}
	default:
		err = &NotSingularError{portfolio.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pq *PortfolioQuery) OnlyIDX(ctx context.Context) int {
	id, err := pq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Portfolios.
func (pq *PortfolioQuery) All(ctx context.Context) ([]*Portfolio, error) {
	if err := pq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pq *PortfolioQuery) AllX(ctx context.Context) []*Portfolio {
	nodes, err := pq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Portfolio IDs.
func (pq *PortfolioQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := pq.Select(portfolio.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pq *PortfolioQuery) IDsX(ctx context.Context) []int {
	ids, err := pq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pq *PortfolioQuery) Count(ctx context.Context) (int, error) {
	if err := pq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pq *PortfolioQuery) CountX(ctx context.Context) int {
	count, err := pq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pq *PortfolioQuery) Exist(ctx context.Context) (bool, error) {
	if err := pq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pq *PortfolioQuery) ExistX(ctx context.Context) bool {
	exist, err := pq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PortfolioQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pq *PortfolioQuery) Clone() *PortfolioQuery {
	if pq == nil {
		return nil
	}
	return &PortfolioQuery{
		config:           pq.config,
		limit:            pq.limit,
		offset:           pq.offset,
		order:            append([]OrderFunc{}, pq.order...),
		predicates:       append([]predicate.Portfolio{}, pq.predicates...),
		withTransactions: pq.withTransactions.Clone(),
		withInvestments:  pq.withInvestments.Clone(),
		withUserID:       pq.withUserID.Clone(),
		// clone intermediate query.
		sql:    pq.sql.Clone(),
		path:   pq.path,
		unique: pq.unique,
	}
}

// WithTransactions tells the query-builder to eager-load the nodes that are connected to
// the "transactions" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PortfolioQuery) WithTransactions(opts ...func(*TransactionQuery)) *PortfolioQuery {
	query := &TransactionQuery{config: pq.config}
	for _, opt := range opts {
		opt(query)
	}
	pq.withTransactions = query
	return pq
}

// WithInvestments tells the query-builder to eager-load the nodes that are connected to
// the "investments" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PortfolioQuery) WithInvestments(opts ...func(*InvestmentQuery)) *PortfolioQuery {
	query := &InvestmentQuery{config: pq.config}
	for _, opt := range opts {
		opt(query)
	}
	pq.withInvestments = query
	return pq
}

// WithUserID tells the query-builder to eager-load the nodes that are connected to
// the "user_id" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PortfolioQuery) WithUserID(opts ...func(*UserQuery)) *PortfolioQuery {
	query := &UserQuery{config: pq.config}
	for _, opt := range opts {
		opt(query)
	}
	pq.withUserID = query
	return pq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Portfolio.Query().
//		GroupBy(portfolio.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pq *PortfolioQuery) GroupBy(field string, fields ...string) *PortfolioGroupBy {
	grbuild := &PortfolioGroupBy{config: pq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pq.sqlQuery(ctx), nil
	}
	grbuild.label = portfolio.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Portfolio.Query().
//		Select(portfolio.FieldName).
//		Scan(ctx, &v)
func (pq *PortfolioQuery) Select(fields ...string) *PortfolioSelect {
	pq.fields = append(pq.fields, fields...)
	selbuild := &PortfolioSelect{PortfolioQuery: pq}
	selbuild.label = portfolio.Label
	selbuild.flds, selbuild.scan = &pq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a PortfolioSelect configured with the given aggregations.
func (pq *PortfolioQuery) Aggregate(fns ...AggregateFunc) *PortfolioSelect {
	return pq.Select().Aggregate(fns...)
}

func (pq *PortfolioQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pq.fields {
		if !portfolio.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pq.path != nil {
		prev, err := pq.path(ctx)
		if err != nil {
			return err
		}
		pq.sql = prev
	}
	return nil
}

func (pq *PortfolioQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Portfolio, error) {
	var (
		nodes       = []*Portfolio{}
		withFKs     = pq.withFKs
		_spec       = pq.querySpec()
		loadedTypes = [3]bool{
			pq.withTransactions != nil,
			pq.withInvestments != nil,
			pq.withUserID != nil,
		}
	)
	if pq.withUserID != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, portfolio.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Portfolio).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Portfolio{config: pq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pq.withTransactions; query != nil {
		if err := pq.loadTransactions(ctx, query, nodes,
			func(n *Portfolio) { n.Edges.Transactions = []*Transaction{} },
			func(n *Portfolio, e *Transaction) { n.Edges.Transactions = append(n.Edges.Transactions, e) }); err != nil {
			return nil, err
		}
	}
	if query := pq.withInvestments; query != nil {
		if err := pq.loadInvestments(ctx, query, nodes,
			func(n *Portfolio) { n.Edges.Investments = []*Investment{} },
			func(n *Portfolio, e *Investment) { n.Edges.Investments = append(n.Edges.Investments, e) }); err != nil {
			return nil, err
		}
	}
	if query := pq.withUserID; query != nil {
		if err := pq.loadUserID(ctx, query, nodes, nil,
			func(n *Portfolio, e *User) { n.Edges.UserID = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pq *PortfolioQuery) loadTransactions(ctx context.Context, query *TransactionQuery, nodes []*Portfolio, init func(*Portfolio), assign func(*Portfolio, *Transaction)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Portfolio)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Transaction(func(s *sql.Selector) {
		s.Where(sql.InValues(portfolio.TransactionsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.portfolio_transactions
		if fk == nil {
			return fmt.Errorf(`foreign-key "portfolio_transactions" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "portfolio_transactions" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (pq *PortfolioQuery) loadInvestments(ctx context.Context, query *InvestmentQuery, nodes []*Portfolio, init func(*Portfolio), assign func(*Portfolio, *Investment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Portfolio)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Investment(func(s *sql.Selector) {
		s.Where(sql.InValues(portfolio.InvestmentsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.portfolio_investments
		if fk == nil {
			return fmt.Errorf(`foreign-key "portfolio_investments" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "portfolio_investments" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (pq *PortfolioQuery) loadUserID(ctx context.Context, query *UserQuery, nodes []*Portfolio, init func(*Portfolio), assign func(*Portfolio, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Portfolio)
	for i := range nodes {
		if nodes[i].user_portfolios == nil {
			continue
		}
		fk := *nodes[i].user_portfolios
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_portfolios" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pq *PortfolioQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pq.querySpec()
	_spec.Node.Columns = pq.fields
	if len(pq.fields) > 0 {
		_spec.Unique = pq.unique != nil && *pq.unique
	}
	return sqlgraph.CountNodes(ctx, pq.driver, _spec)
}

func (pq *PortfolioQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := pq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (pq *PortfolioQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   portfolio.Table,
			Columns: portfolio.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: portfolio.FieldID,
			},
		},
		From:   pq.sql,
		Unique: true,
	}
	if unique := pq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, portfolio.FieldID)
		for i := range fields {
			if fields[i] != portfolio.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pq *PortfolioQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pq.driver.Dialect())
	t1 := builder.Table(portfolio.Table)
	columns := pq.fields
	if len(columns) == 0 {
		columns = portfolio.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pq.sql != nil {
		selector = pq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pq.unique != nil && *pq.unique {
		selector.Distinct()
	}
	for _, p := range pq.predicates {
		p(selector)
	}
	for _, p := range pq.order {
		p(selector)
	}
	if offset := pq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PortfolioGroupBy is the group-by builder for Portfolio entities.
type PortfolioGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pgb *PortfolioGroupBy) Aggregate(fns ...AggregateFunc) *PortfolioGroupBy {
	pgb.fns = append(pgb.fns, fns...)
	return pgb
}

// Scan applies the group-by query and scans the result into the given value.
func (pgb *PortfolioGroupBy) Scan(ctx context.Context, v any) error {
	query, err := pgb.path(ctx)
	if err != nil {
		return err
	}
	pgb.sql = query
	return pgb.sqlScan(ctx, v)
}

func (pgb *PortfolioGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range pgb.fields {
		if !portfolio.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pgb *PortfolioGroupBy) sqlQuery() *sql.Selector {
	selector := pgb.sql.Select()
	aggregation := make([]string, 0, len(pgb.fns))
	for _, fn := range pgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pgb.fields)+len(pgb.fns))
		for _, f := range pgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pgb.fields...)...)
}

// PortfolioSelect is the builder for selecting fields of Portfolio entities.
type PortfolioSelect struct {
	*PortfolioQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ps *PortfolioSelect) Aggregate(fns ...AggregateFunc) *PortfolioSelect {
	ps.fns = append(ps.fns, fns...)
	return ps
}

// Scan applies the selector query and scans the result into the given value.
func (ps *PortfolioSelect) Scan(ctx context.Context, v any) error {
	if err := ps.prepareQuery(ctx); err != nil {
		return err
	}
	ps.sql = ps.PortfolioQuery.sqlQuery(ctx)
	return ps.sqlScan(ctx, v)
}

func (ps *PortfolioSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(ps.fns))
	for _, fn := range ps.fns {
		aggregation = append(aggregation, fn(ps.sql))
	}
	switch n := len(*ps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		ps.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		ps.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := ps.sql.Query()
	if err := ps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
