// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/investment"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/portfolio"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/schema"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/transaction"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	investmentFields := schema.Investment{}.Fields()
	_ = investmentFields
	// investmentDescCreatedAt is the schema descriptor for created_at field.
	investmentDescCreatedAt := investmentFields[8].Descriptor()
	// investment.DefaultCreatedAt holds the default value on creation for the created_at field.
	investment.DefaultCreatedAt = investmentDescCreatedAt.Default.(func() time.Time)
	// investmentDescUpdatedAt is the schema descriptor for updated_at field.
	investmentDescUpdatedAt := investmentFields[9].Descriptor()
	// investment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	investment.DefaultUpdatedAt = investmentDescUpdatedAt.Default.(func() time.Time)
	portfolioFields := schema.Portfolio{}.Fields()
	_ = portfolioFields
	// portfolioDescCreatedAt is the schema descriptor for created_at field.
	portfolioDescCreatedAt := portfolioFields[4].Descriptor()
	// portfolio.DefaultCreatedAt holds the default value on creation for the created_at field.
	portfolio.DefaultCreatedAt = portfolioDescCreatedAt.Default.(func() time.Time)
	// portfolioDescUpdatedAt is the schema descriptor for updated_at field.
	portfolioDescUpdatedAt := portfolioFields[5].Descriptor()
	// portfolio.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	portfolio.DefaultUpdatedAt = portfolioDescUpdatedAt.Default.(func() time.Time)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionFields[7].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(func() time.Time)
	// transactionDescUpdatedAt is the schema descriptor for updated_at field.
	transactionDescUpdatedAt := transactionFields[8].Descriptor()
	// transaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	transaction.DefaultUpdatedAt = transactionDescUpdatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[10].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[11].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
}
