// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/portfolio"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/predicate"
	"github.com/lostintheway/shareapp/tree/shareapp_go_ent/ent/transaction"
)

// TransactionUpdate is the builder for updating Transaction entities.
type TransactionUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionMutation
}

// Where appends a list predicates to the TransactionUpdate builder.
func (tu *TransactionUpdate) Where(ps ...predicate.Transaction) *TransactionUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetShareName sets the "shareName" field.
func (tu *TransactionUpdate) SetShareName(s string) *TransactionUpdate {
	tu.mutation.SetShareName(s)
	return tu
}

// SetDate sets the "date" field.
func (tu *TransactionUpdate) SetDate(t time.Time) *TransactionUpdate {
	tu.mutation.SetDate(t)
	return tu
}

// SetQuantity sets the "quantity" field.
func (tu *TransactionUpdate) SetQuantity(i int) *TransactionUpdate {
	tu.mutation.ResetQuantity()
	tu.mutation.SetQuantity(i)
	return tu
}

// AddQuantity adds i to the "quantity" field.
func (tu *TransactionUpdate) AddQuantity(i int) *TransactionUpdate {
	tu.mutation.AddQuantity(i)
	return tu
}

// SetPrice sets the "price" field.
func (tu *TransactionUpdate) SetPrice(i int) *TransactionUpdate {
	tu.mutation.ResetPrice()
	tu.mutation.SetPrice(i)
	return tu
}

// AddPrice adds i to the "price" field.
func (tu *TransactionUpdate) AddPrice(i int) *TransactionUpdate {
	tu.mutation.AddPrice(i)
	return tu
}

// SetTransType sets the "trans_type" field.
func (tu *TransactionUpdate) SetTransType(s string) *TransactionUpdate {
	tu.mutation.SetTransType(s)
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TransactionUpdate) SetUpdatedAt(t time.Time) *TransactionUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableUpdatedAt(t *time.Time) *TransactionUpdate {
	if t != nil {
		tu.SetUpdatedAt(*t)
	}
	return tu
}

// SetPfIDID sets the "pf_id" edge to the Portfolio entity by ID.
func (tu *TransactionUpdate) SetPfIDID(id int) *TransactionUpdate {
	tu.mutation.SetPfIDID(id)
	return tu
}

// SetNillablePfIDID sets the "pf_id" edge to the Portfolio entity by ID if the given value is not nil.
func (tu *TransactionUpdate) SetNillablePfIDID(id *int) *TransactionUpdate {
	if id != nil {
		tu = tu.SetPfIDID(*id)
	}
	return tu
}

// SetPfID sets the "pf_id" edge to the Portfolio entity.
func (tu *TransactionUpdate) SetPfID(p *Portfolio) *TransactionUpdate {
	return tu.SetPfIDID(p.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (tu *TransactionUpdate) Mutation() *TransactionMutation {
	return tu.mutation
}

// ClearPfID clears the "pf_id" edge to the Portfolio entity.
func (tu *TransactionUpdate) ClearPfID() *TransactionUpdate {
	tu.mutation.ClearPfID()
	return tu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TransactionUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tu.hooks) == 0 {
		affected, err = tu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TransactionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tu.mutation = mutation
			affected, err = tu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tu.hooks) - 1; i >= 0; i-- {
			if tu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TransactionUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TransactionUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TransactionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   transaction.Table,
			Columns: transaction.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: transaction.FieldID,
			},
		},
	}
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.ShareName(); ok {
		_spec.SetField(transaction.FieldShareName, field.TypeString, value)
	}
	if value, ok := tu.mutation.Date(); ok {
		_spec.SetField(transaction.FieldDate, field.TypeTime, value)
	}
	if value, ok := tu.mutation.Quantity(); ok {
		_spec.SetField(transaction.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedQuantity(); ok {
		_spec.AddField(transaction.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := tu.mutation.Price(); ok {
		_spec.SetField(transaction.FieldPrice, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedPrice(); ok {
		_spec.AddField(transaction.FieldPrice, field.TypeInt, value)
	}
	if value, ok := tu.mutation.TransType(); ok {
		_spec.SetField(transaction.FieldTransType, field.TypeString, value)
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(transaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if tu.mutation.PfIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.PfIDTable,
			Columns: []string{transaction.PfIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: portfolio.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.PfIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.PfIDTable,
			Columns: []string{transaction.PfIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: portfolio.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// TransactionUpdateOne is the builder for updating a single Transaction entity.
type TransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionMutation
}

// SetShareName sets the "shareName" field.
func (tuo *TransactionUpdateOne) SetShareName(s string) *TransactionUpdateOne {
	tuo.mutation.SetShareName(s)
	return tuo
}

// SetDate sets the "date" field.
func (tuo *TransactionUpdateOne) SetDate(t time.Time) *TransactionUpdateOne {
	tuo.mutation.SetDate(t)
	return tuo
}

// SetQuantity sets the "quantity" field.
func (tuo *TransactionUpdateOne) SetQuantity(i int) *TransactionUpdateOne {
	tuo.mutation.ResetQuantity()
	tuo.mutation.SetQuantity(i)
	return tuo
}

// AddQuantity adds i to the "quantity" field.
func (tuo *TransactionUpdateOne) AddQuantity(i int) *TransactionUpdateOne {
	tuo.mutation.AddQuantity(i)
	return tuo
}

// SetPrice sets the "price" field.
func (tuo *TransactionUpdateOne) SetPrice(i int) *TransactionUpdateOne {
	tuo.mutation.ResetPrice()
	tuo.mutation.SetPrice(i)
	return tuo
}

// AddPrice adds i to the "price" field.
func (tuo *TransactionUpdateOne) AddPrice(i int) *TransactionUpdateOne {
	tuo.mutation.AddPrice(i)
	return tuo
}

// SetTransType sets the "trans_type" field.
func (tuo *TransactionUpdateOne) SetTransType(s string) *TransactionUpdateOne {
	tuo.mutation.SetTransType(s)
	return tuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TransactionUpdateOne) SetUpdatedAt(t time.Time) *TransactionUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableUpdatedAt(t *time.Time) *TransactionUpdateOne {
	if t != nil {
		tuo.SetUpdatedAt(*t)
	}
	return tuo
}

// SetPfIDID sets the "pf_id" edge to the Portfolio entity by ID.
func (tuo *TransactionUpdateOne) SetPfIDID(id int) *TransactionUpdateOne {
	tuo.mutation.SetPfIDID(id)
	return tuo
}

// SetNillablePfIDID sets the "pf_id" edge to the Portfolio entity by ID if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillablePfIDID(id *int) *TransactionUpdateOne {
	if id != nil {
		tuo = tuo.SetPfIDID(*id)
	}
	return tuo
}

// SetPfID sets the "pf_id" edge to the Portfolio entity.
func (tuo *TransactionUpdateOne) SetPfID(p *Portfolio) *TransactionUpdateOne {
	return tuo.SetPfIDID(p.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (tuo *TransactionUpdateOne) Mutation() *TransactionMutation {
	return tuo.mutation
}

// ClearPfID clears the "pf_id" edge to the Portfolio entity.
func (tuo *TransactionUpdateOne) ClearPfID() *TransactionUpdateOne {
	tuo.mutation.ClearPfID()
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TransactionUpdateOne) Select(field string, fields ...string) *TransactionUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Transaction entity.
func (tuo *TransactionUpdateOne) Save(ctx context.Context) (*Transaction, error) {
	var (
		err  error
		node *Transaction
	)
	if len(tuo.hooks) == 0 {
		node, err = tuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TransactionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tuo.mutation = mutation
			node, err = tuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tuo.hooks) - 1; i >= 0; i-- {
			if tuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, tuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Transaction)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from TransactionMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TransactionUpdateOne) SaveX(ctx context.Context) *Transaction {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TransactionUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TransactionUpdateOne) sqlSave(ctx context.Context) (_node *Transaction, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   transaction.Table,
			Columns: transaction.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: transaction.FieldID,
			},
		},
	}
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for _, f := range fields {
			if !transaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.ShareName(); ok {
		_spec.SetField(transaction.FieldShareName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Date(); ok {
		_spec.SetField(transaction.FieldDate, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.Quantity(); ok {
		_spec.SetField(transaction.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedQuantity(); ok {
		_spec.AddField(transaction.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.Price(); ok {
		_spec.SetField(transaction.FieldPrice, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedPrice(); ok {
		_spec.AddField(transaction.FieldPrice, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.TransType(); ok {
		_spec.SetField(transaction.FieldTransType, field.TypeString, value)
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(transaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if tuo.mutation.PfIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.PfIDTable,
			Columns: []string{transaction.PfIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: portfolio.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.PfIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.PfIDTable,
			Columns: []string{transaction.PfIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: portfolio.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Transaction{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
