// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Investment is the predicate function for investment builders.
type Investment func(*sql.Selector)

// Portfolio is the predicate function for portfolio builders.
type Portfolio func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
